import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "@/components/NavBar/index";
import Footer from "@/components/Footer/index";
import UserProvider from "@/context/userContext";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <UserProvider>
      <html lang="en" className={inter.className}>
        <body className="container">
          <NavBar />
          {children}
          <Footer />
        </body>
      </html>
    </UserProvider>
  );
}
